import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavLayout } from "./nav-layout";
import Preloader from "@/components/Preloader";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { AuthProvider } from '@/context/AuthContext';

// config.autoAddCss = false

export const metadata: Metadata = {
  title: "SUPER SEVEN STUDIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        <AuthProvider>
          <NavLayout>{children}</NavLayout>
        </AuthProvider>
        
      </body>
    </html>
  );
}
